/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCard: typeof import('./src/components/teamCard.vue')['default']
    TeamInfo: typeof import('./src/components/TeamInfo.vue')['default']
    TeamStat: typeof import('./src/components/TeamStat.vue')['default']
    TeamStats: typeof import('./src/components/TeamStats.vue')['default']
  }
}
